environment:
  nodejs_version: "8"

only_commits:
  message: /[deploy]/

skip_branch_with_pr: true

branches:
  only:
  - master

build: off

install:
  - ps: Install-Product node $env:nodejs_version

before_test:
  - npm install -g eslint
  - npm install -g eslint-plugin-promise@latest
  - npm install -g firebase-tools
  - cmd: chdir functions
  - cmd: npm install

test_script:
- firebase deploy --token %DEPLOY_TOKEN%
